// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'inspecao.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_Inspecao _$InspecaoFromJson(Map<String, dynamic> json) => _Inspecao(
  id: (json['id'] as num?)?.toInt(),
  nrInspecao: (json['nrInspecao'] as num).toDouble(),
  dtAberturaInspecao: DateTime.parse(json['dtAberturaInspecao'] as String),
  cdUnConsumidora: (json['cdUnConsumidora'] as num).toDouble(),
  nrPdaCarga: (json['nrPdaCarga'] as num).toDouble(),
  cdConsumidor: (json['cdConsumidor'] as num).toDouble(),
  cdClasse: (json['cdClasse'] as num?)?.toDouble(),
  tpFase: json['tpFase'] as String?,
  nrMedidorKwh: (json['nrMedidorKwh'] as num?)?.toDouble(),
  nrMedidorKvarh: (json['nrMedidorKvarh'] as num?)?.toDouble(),
  vlConstKwhPonta: (json['vlConstKwhPonta'] as num?)?.toDouble(),
  vlConstKwhForaPonta: (json['vlConstKwhForaPonta'] as num?)?.toDouble(),
  vlConstKwhGeral: (json['vlConstKwhGeral'] as num?)?.toDouble(),
  vlConstKwPonta: (json['vlConstKwPonta'] as num?)?.toDouble(),
  vlConstKwForaPonta: (json['vlConstKwForaPonta'] as num?)?.toDouble(),
  vlConstKwGeral: (json['vlConstKwGeral'] as num?)?.toDouble(),
  vlConstKvarhPonta: (json['vlConstKvarhPonta'] as num?)?.toDouble(),
  vlConstKvarhForaPonta: (json['vlConstKvarhForaPonta'] as num?)?.toDouble(),
  vlConstKvarhGeral: (json['vlConstKvarhGeral'] as num?)?.toDouble(),
  vlConstEspecial: (json['vlConstEspecial'] as num?)?.toDouble(),
  flLacreCxPadrao: json['flLacreCxPadrao'] as String?,
  flLacreMedidores: json['flLacreMedidores'] as String?,
  flRotacaoMedidores: json['flRotacaoMedidores'] as String?,
  dtConclusaoInspecao: json['dtConclusaoInspecao'] == null
      ? null
      : DateTime.parse(json['dtConclusaoInspecao'] as String),
  cdInspetor: (json['cdInspetor'] as num?)?.toDouble(),
  idUsuario: json['idUsuario'] as String?,
  flSituacao: (json['flSituacao'] as num?)?.toDouble(),
  dsObservacao: json['dsObservacao'] as String?,
  hrAberturaInspecao: json['hrAberturaInspecao'] as String?,
  hrConclusaoInspecao: json['hrConclusaoInspecao'] as String?,
  idUsuarioAbertura: json['idUsuarioAbertura'] as String?,
  idUsuarioConclusao: json['idUsuarioConclusao'] as String?,
  dtCancelamento: json['dtCancelamento'] == null
      ? null
      : DateTime.parse(json['dtCancelamento'] as String),
  idUsuarioCancelamento: json['idUsuarioCancelamento'] as String?,
  anoReferencia: (json['anoReferencia'] as num?)?.toDouble(),
  dtInspecao: json['dtInspecao'] == null
      ? null
      : DateTime.parse(json['dtInspecao'] as String),
  vlConstMedidor: (json['vlConstMedidor'] as num?)?.toDouble(),
  vlLacreCaixa: (json['vlLacreCaixa'] as num?)?.toDouble(),
  flResultado: (json['flResultado'] as num?)?.toDouble(),
  flGeraFatura: json['flGeraFatura'] as String?,
  vlConstMedidorKvarh: (json['vlConstMedidorKvarh'] as num?)?.toDouble(),
  vlConstMedidorEsp: (json['vlConstMedidorEsp'] as num?)?.toDouble(),
  vlLacreMedidor5: (json['vlLacreMedidor5'] as num?)?.toDouble(),
  dsIrregularidades: json['dsIrregularidades'] as String?,
  vlLacreCaixa1: (json['vlLacreCaixa1'] as num?)?.toDouble(),
  vlLacreReativo: (json['vlLacreReativo'] as num?)?.toDouble(),
  vlLacreReativo1: (json['vlLacreReativo1'] as num?)?.toDouble(),
  vlLacreTcs: (json['vlLacreTcs'] as num?)?.toDouble(),
  vlLacreTcs1: (json['vlLacreTcs1'] as num?)?.toDouble(),
  flLacreControlado: json['flLacreControlado'] as String?,
  dtLacreControlado: json['dtLacreControlado'] == null
      ? null
      : DateTime.parse(json['dtLacreControlado'] as String),
  flMotivoInspecao: (json['flMotivoInspecao'] as num?)?.toDouble(),
  flMonitoramento: json['flMonitoramento'] as String?,
  vlLacreControlado: (json['vlLacreControlado'] as num?)?.toDouble(),
  flDeficienciaMedicao: json['flDeficienciaMedicao'] as String?,
  flFaturamentoIncorreto: json['flFaturamentoIncorreto'] as String?,
  vlLacreConfMedAtivo1: json['vlLacreConfMedAtivo1'] as String?,
  vlLacreConfMedAtivo2: json['vlLacreConfMedAtivo2'] as String?,
  vlLacreConfMedAtivo3: json['vlLacreConfMedAtivo3'] as String?,
  vlLacreConfMedAtivo4: json['vlLacreConfMedAtivo4'] as String?,
  vlLacreConfMedReativo1: json['vlLacreConfMedReativo1'] as String?,
  vlLacreConfMedReativo2: json['vlLacreConfMedReativo2'] as String?,
  vlLacreConfMedReativo3: json['vlLacreConfMedReativo3'] as String?,
  vlLacreConfMedReativo4: json['vlLacreConfMedReativo4'] as String?,
  vlLacreMedidor1: json['vlLacreMedidor1'] as String?,
  vlLacreMedidor2: json['vlLacreMedidor2'] as String?,
  vlLacreMedidor3: json['vlLacreMedidor3'] as String?,
  vlLacreMedidor4: json['vlLacreMedidor4'] as String?,
  vlLacreMedidorKvarh1: json['vlLacreMedidorKvarh1'] as String?,
  vlLacreMedidorKvarh2: json['vlLacreMedidorKvarh2'] as String?,
  vlLacreMedidorKvarh3: json['vlLacreMedidorKvarh3'] as String?,
  vlLacreMedidorKvarh4: json['vlLacreMedidorKvarh4'] as String?,
  flPendencias: json['flPendencias'] as String?,
  dsPendencias: json['dsPendencias'] as String?,
  dsObservacaoMotivo: json['dsObservacaoMotivo'] as String?,
  tpInspecao: (json['tpInspecao'] as num).toDouble(),
  cdEmpresa: (json['cdEmpresa'] as num?)?.toDouble(),
  dsRua: json['dsRua'] as String,
  dsComplemento: json['dsComplemento'] as String?,
  dsBairro: json['dsBairro'] as String,
  dsMunicipio: json['dsMunicipio'] as String,
  cdEstado: json['cdEstado'] as String,
  longitude: (json['longitude'] as num).toDouble(),
  latitude: (json['latitude'] as num).toDouble(),
  dsNumero: (json['dsNumero'] as num).toDouble(),
  cdCep: (json['cdCep'] as num).toDouble(),
  cdCompCep: (json['cdCompCep'] as num?)?.toDouble(),
  cdMunicipio: (json['cdMunicipio'] as num).toDouble(),
  flCarregadoPda: json['flCarregadoPda'] as String,
  nrCgcCpf: (json['nrCgcCpf'] as num?)?.toDouble(),
  dsPostoTransformador: json['dsPostoTransformador'] as String?,
  dsConsumidor: json['dsConsumidor'] as String?,
  nrIe: json['nrIe'] as String?,
  dsClasse: json['dsClasse'] as String?,
  vlTensaoNominal: json['vlTensaoNominal'] as String?,
  vlUltConstKwhPonta: (json['vlUltConstKwhPonta'] as num?)?.toDouble(),
  vlUltLeitKwhPonta: (json['vlUltLeitKwhPonta'] as num?)?.toDouble(),
  vlUltConstKwhForaPonta: (json['vlUltConstKwhForaPonta'] as num?)?.toDouble(),
  vlUltLeitKwhForaPonta: (json['vlUltLeitKwhForaPonta'] as num?)?.toDouble(),
  vlUltConstKwhGeral: (json['vlUltConstKwhGeral'] as num?)?.toDouble(),
  vlUltLeitKwhGeral: (json['vlUltLeitKwhGeral'] as num?)?.toDouble(),
  vlUltConstEspecial: (json['vlUltConstEspecial'] as num?)?.toDouble(),
  vlUltLeitEspecial: (json['vlUltLeitEspecial'] as num?)?.toDouble(),
  vlUltConstKvarhPonta: (json['vlUltConstKvarhPonta'] as num?)?.toDouble(),
  vlUltLeitKvarhPonta: (json['vlUltLeitKvarhPonta'] as num?)?.toDouble(),
  vlUltConstKvarhForaPonta: (json['vlUltConstKvarhForaPonta'] as num?)
      ?.toDouble(),
  vlUltLeitKvarhForaPonta: (json['vlUltLeitKvarhForaPonta'] as num?)
      ?.toDouble(),
  vlUltConstKvarhGeral: (json['vlUltConstKvarhGeral'] as num?)?.toDouble(),
  vlUltLeitKvarhGeral: (json['vlUltLeitKvarhGeral'] as num?)?.toDouble(),
  vlUltConstKwPonta: (json['vlUltConstKwPonta'] as num?)?.toDouble(),
  vlUltLeitKwPonta: (json['vlUltLeitKwPonta'] as num?)?.toDouble(),
  vlUltConstKwForaPonta: (json['vlUltConstKwForaPonta'] as num?)?.toDouble(),
  vlUltLeitKwForaPonta: (json['vlUltLeitKwForaPonta'] as num?)?.toDouble(),
  vlUltConstKwGeral: (json['vlUltConstKwGeral'] as num?)?.toDouble(),
  vlUltLeitKwGeral: (json['vlUltLeitKwGeral'] as num?)?.toDouble(),
  conclusao: json['conclusao'] == null
      ? null
      : InspecaoConclusao.fromJson(json['conclusao'] as Map<String, dynamic>),
  cdTipoOcorrencia: (json['cdTipoOcorrencia'] as num?)?.toInt(),
  dsComplementarOcorrencia: json['dsComplementarOcorrencia'] as String?,
  status: (json['status'] as num?)?.toInt() ?? 0,
);

Map<String, dynamic> _$InspecaoToJson(_Inspecao instance) => <String, dynamic>{
  'id': instance.id,
  'nrInspecao': instance.nrInspecao,
  'dtAberturaInspecao': instance.dtAberturaInspecao.toIso8601String(),
  'cdUnConsumidora': instance.cdUnConsumidora,
  'nrPdaCarga': instance.nrPdaCarga,
  'cdConsumidor': instance.cdConsumidor,
  'cdClasse': instance.cdClasse,
  'tpFase': instance.tpFase,
  'nrMedidorKwh': instance.nrMedidorKwh,
  'nrMedidorKvarh': instance.nrMedidorKvarh,
  'vlConstKwhPonta': instance.vlConstKwhPonta,
  'vlConstKwhForaPonta': instance.vlConstKwhForaPonta,
  'vlConstKwhGeral': instance.vlConstKwhGeral,
  'vlConstKwPonta': instance.vlConstKwPonta,
  'vlConstKwForaPonta': instance.vlConstKwForaPonta,
  'vlConstKwGeral': instance.vlConstKwGeral,
  'vlConstKvarhPonta': instance.vlConstKvarhPonta,
  'vlConstKvarhForaPonta': instance.vlConstKvarhForaPonta,
  'vlConstKvarhGeral': instance.vlConstKvarhGeral,
  'vlConstEspecial': instance.vlConstEspecial,
  'flLacreCxPadrao': instance.flLacreCxPadrao,
  'flLacreMedidores': instance.flLacreMedidores,
  'flRotacaoMedidores': instance.flRotacaoMedidores,
  'dtConclusaoInspecao': instance.dtConclusaoInspecao?.toIso8601String(),
  'cdInspetor': instance.cdInspetor,
  'idUsuario': instance.idUsuario,
  'flSituacao': instance.flSituacao,
  'dsObservacao': instance.dsObservacao,
  'hrAberturaInspecao': instance.hrAberturaInspecao,
  'hrConclusaoInspecao': instance.hrConclusaoInspecao,
  'idUsuarioAbertura': instance.idUsuarioAbertura,
  'idUsuarioConclusao': instance.idUsuarioConclusao,
  'dtCancelamento': instance.dtCancelamento?.toIso8601String(),
  'idUsuarioCancelamento': instance.idUsuarioCancelamento,
  'anoReferencia': instance.anoReferencia,
  'dtInspecao': instance.dtInspecao?.toIso8601String(),
  'vlConstMedidor': instance.vlConstMedidor,
  'vlLacreCaixa': instance.vlLacreCaixa,
  'flResultado': instance.flResultado,
  'flGeraFatura': instance.flGeraFatura,
  'vlConstMedidorKvarh': instance.vlConstMedidorKvarh,
  'vlConstMedidorEsp': instance.vlConstMedidorEsp,
  'vlLacreMedidor5': instance.vlLacreMedidor5,
  'dsIrregularidades': instance.dsIrregularidades,
  'vlLacreCaixa1': instance.vlLacreCaixa1,
  'vlLacreReativo': instance.vlLacreReativo,
  'vlLacreReativo1': instance.vlLacreReativo1,
  'vlLacreTcs': instance.vlLacreTcs,
  'vlLacreTcs1': instance.vlLacreTcs1,
  'flLacreControlado': instance.flLacreControlado,
  'dtLacreControlado': instance.dtLacreControlado?.toIso8601String(),
  'flMotivoInspecao': instance.flMotivoInspecao,
  'flMonitoramento': instance.flMonitoramento,
  'vlLacreControlado': instance.vlLacreControlado,
  'flDeficienciaMedicao': instance.flDeficienciaMedicao,
  'flFaturamentoIncorreto': instance.flFaturamentoIncorreto,
  'vlLacreConfMedAtivo1': instance.vlLacreConfMedAtivo1,
  'vlLacreConfMedAtivo2': instance.vlLacreConfMedAtivo2,
  'vlLacreConfMedAtivo3': instance.vlLacreConfMedAtivo3,
  'vlLacreConfMedAtivo4': instance.vlLacreConfMedAtivo4,
  'vlLacreConfMedReativo1': instance.vlLacreConfMedReativo1,
  'vlLacreConfMedReativo2': instance.vlLacreConfMedReativo2,
  'vlLacreConfMedReativo3': instance.vlLacreConfMedReativo3,
  'vlLacreConfMedReativo4': instance.vlLacreConfMedReativo4,
  'vlLacreMedidor1': instance.vlLacreMedidor1,
  'vlLacreMedidor2': instance.vlLacreMedidor2,
  'vlLacreMedidor3': instance.vlLacreMedidor3,
  'vlLacreMedidor4': instance.vlLacreMedidor4,
  'vlLacreMedidorKvarh1': instance.vlLacreMedidorKvarh1,
  'vlLacreMedidorKvarh2': instance.vlLacreMedidorKvarh2,
  'vlLacreMedidorKvarh3': instance.vlLacreMedidorKvarh3,
  'vlLacreMedidorKvarh4': instance.vlLacreMedidorKvarh4,
  'flPendencias': instance.flPendencias,
  'dsPendencias': instance.dsPendencias,
  'dsObservacaoMotivo': instance.dsObservacaoMotivo,
  'tpInspecao': instance.tpInspecao,
  'cdEmpresa': instance.cdEmpresa,
  'dsRua': instance.dsRua,
  'dsComplemento': instance.dsComplemento,
  'dsBairro': instance.dsBairro,
  'dsMunicipio': instance.dsMunicipio,
  'cdEstado': instance.cdEstado,
  'longitude': instance.longitude,
  'latitude': instance.latitude,
  'dsNumero': instance.dsNumero,
  'cdCep': instance.cdCep,
  'cdCompCep': instance.cdCompCep,
  'cdMunicipio': instance.cdMunicipio,
  'flCarregadoPda': instance.flCarregadoPda,
  'nrCgcCpf': instance.nrCgcCpf,
  'dsPostoTransformador': instance.dsPostoTransformador,
  'dsConsumidor': instance.dsConsumidor,
  'nrIe': instance.nrIe,
  'dsClasse': instance.dsClasse,
  'vlTensaoNominal': instance.vlTensaoNominal,
  'vlUltConstKwhPonta': instance.vlUltConstKwhPonta,
  'vlUltLeitKwhPonta': instance.vlUltLeitKwhPonta,
  'vlUltConstKwhForaPonta': instance.vlUltConstKwhForaPonta,
  'vlUltLeitKwhForaPonta': instance.vlUltLeitKwhForaPonta,
  'vlUltConstKwhGeral': instance.vlUltConstKwhGeral,
  'vlUltLeitKwhGeral': instance.vlUltLeitKwhGeral,
  'vlUltConstEspecial': instance.vlUltConstEspecial,
  'vlUltLeitEspecial': instance.vlUltLeitEspecial,
  'vlUltConstKvarhPonta': instance.vlUltConstKvarhPonta,
  'vlUltLeitKvarhPonta': instance.vlUltLeitKvarhPonta,
  'vlUltConstKvarhForaPonta': instance.vlUltConstKvarhForaPonta,
  'vlUltLeitKvarhForaPonta': instance.vlUltLeitKvarhForaPonta,
  'vlUltConstKvarhGeral': instance.vlUltConstKvarhGeral,
  'vlUltLeitKvarhGeral': instance.vlUltLeitKvarhGeral,
  'vlUltConstKwPonta': instance.vlUltConstKwPonta,
  'vlUltLeitKwPonta': instance.vlUltLeitKwPonta,
  'vlUltConstKwForaPonta': instance.vlUltConstKwForaPonta,
  'vlUltLeitKwForaPonta': instance.vlUltLeitKwForaPonta,
  'vlUltConstKwGeral': instance.vlUltConstKwGeral,
  'vlUltLeitKwGeral': instance.vlUltLeitKwGeral,
  'conclusao': instance.conclusao,
  'cdTipoOcorrencia': instance.cdTipoOcorrencia,
  'dsComplementarOcorrencia': instance.dsComplementarOcorrencia,
  'status': instance.status,
};
