// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'inspecao_conclusao.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_InspecaoConclusao _$InspecaoConclusaoFromJson(
  Map<String, dynamic> json,
) => _InspecaoConclusao(
  id: (json['id'] as num?)?.toInt(),
  dtInicio: DateTime.parse(json['dtInicio'] as String),
  dtFim: json['dtFim'] == null ? null : DateTime.parse(json['dtFim'] as String),
  dsObservacao: json['dsObservacao'] as String?,
  vlTc1: json['vlTc1'] as String?,
  vlTc2: json['vlTc2'] as String?,
  vlTp1: json['vlTp1'] as String?,
  vlTp2: json['vlTp2'] as String?,
  vlCorrenteMaxima: json['vlCorrenteMaxima'] as String?,
  vlCorrenteMaximaFim: json['vlCorrenteMaximaFim'] as String?,
  vlCorrenteDisjuntor: json['vlCorrenteDisjuntor'] as String?,
  vlChaveProtecao: json['vlChaveProtecao'] as String?,
  vlCaboEntrada: json['vlCaboEntrada'] as String?,
  vlLacAdicPadAtivo1: json['vlLacAdicPadAtivo1'] as String?,
  vlLacAdicPadAtivo2: json['vlLacAdicPadAtivo2'] as String?,
  vlLacAdicPadAtivo3: json['vlLacAdicPadAtivo3'] as String?,
  vlLacAdicPadAtivo4: json['vlLacAdicPadAtivo4'] as String?,
  vlLacAdicPadReativo1: json['vlLacAdicPadReativo1'] as String?,
  vlLacAdicPadReativo2: json['vlLacAdicPadReativo2'] as String?,
  vlLacAdicPadReativo3: json['vlLacAdicPadReativo3'] as String?,
  vlLacAdicPadReativo4: json['vlLacAdicPadReativo4'] as String?,
  vlLacreAdicTcs1: json['vlLacreAdicTcs1'] as String?,
  vlLacreAdicTcs2: json['vlLacreAdicTcs2'] as String?,
  vlLacreAdicTcs3: json['vlLacreAdicTcs3'] as String?,
  vlLacreAdicTcs4: json['vlLacreAdicTcs4'] as String?,
  vlLacAdicCxDeriva1: json['vlLacAdicCxDeriva1'] as String?,
  vlLacAdicCxDeriva2: json['vlLacAdicCxDeriva2'] as String?,
  vlLacAdicChaveProt1: json['vlLacAdicChaveProt1'] as String?,
  vlLacAdicChaveProt2: json['vlLacAdicChaveProt2'] as String?,
  vlLacreAdicBorne1: json['vlLacreAdicBorne1'] as String?,
  vlLacreAdicBorne2: json['vlLacreAdicBorne2'] as String?,
  vlLacreAdicBorne3: json['vlLacreAdicBorne3'] as String?,
  vlLacreAdicBorne4: json['vlLacreAdicBorne4'] as String?,
  vlLacreAdicChaveAfer1: json['vlLacreAdicChaveAfer1'] as String?,
  vlLacreAdicChaveAfer2: json['vlLacreAdicChaveAfer2'] as String?,
  vlLacreAdicDemanda: json['vlLacreAdicDemanda'] as String?,
  vlLacreAdicDisplay: json['vlLacreAdicDisplay'] as String?,
  vlLacreAdicPortaOptica: json['vlLacreAdicPortaOptica'] as String?,
  vlLacreAdicCubiculo1: json['vlLacreAdicCubiculo1'] as String?,
  vlLacreAdicCubiculo2: json['vlLacreAdicCubiculo2'] as String?,
  vlLacreAdicCxBarram1: json['vlLacreAdicCxBarram1'] as String?,
  vlLacreAdicCxBarram2: json['vlLacreAdicCxBarram2'] as String?,
  vlLacreAdicCxBarram3: json['vlLacreAdicCxBarram3'] as String?,
  vlLacreAdicCxBarram4: json['vlLacreAdicCxBarram4'] as String?,
  vlLacreRetPadAtivo1: json['vlLacreRetPadAtivo1'] as String?,
  vlLacreRetPadAtivo2: json['vlLacreRetPadAtivo2'] as String?,
  vlLacreRetPadAtivo3: json['vlLacreRetPadAtivo3'] as String?,
  vlLacreRetPadAtivo4: json['vlLacreRetPadAtivo4'] as String?,
  vlLacreRetPadReativo1: json['vlLacreRetPadReativo1'] as String?,
  vlLacreRetPadReativo2: json['vlLacreRetPadReativo2'] as String?,
  vlLacreRetPadReativo3: json['vlLacreRetPadReativo3'] as String?,
  vlLacreRetPadReativo4: json['vlLacreRetPadReativo4'] as String?,
  vlLacreRetTcs1: json['vlLacreRetTcs1'] as String?,
  vlLacreRetTcs2: json['vlLacreRetTcs2'] as String?,
  vlLacreRetTcs3: json['vlLacreRetTcs3'] as String?,
  vlLacreRetTcs4: json['vlLacreRetTcs4'] as String?,
  vlLacreRetCaixaDeriva1: json['vlLacreRetCaixaDeriva1'] as String?,
  vlLacreRetCaixaDeriva2: json['vlLacreRetCaixaDeriva2'] as String?,
  vlLacreRetChaveProtec1: json['vlLacreRetChaveProtec1'] as String?,
  vlLacreRetChaveProtec2: json['vlLacreRetChaveProtec2'] as String?,
  vlLacreRetBorne1: json['vlLacreRetBorne1'] as String?,
  vlLacreRetBorne2: json['vlLacreRetBorne2'] as String?,
  vlLacreRetBorne3: json['vlLacreRetBorne3'] as String?,
  vlLacreRetBorne4: json['vlLacreRetBorne4'] as String?,
  vlLacreRetChaveAfer1: json['vlLacreRetChaveAfer1'] as String?,
  vlLacreRetChaveAfer2: json['vlLacreRetChaveAfer2'] as String?,
  vlLacreRetDemanda: json['vlLacreRetDemanda'] as String?,
  vlLacreRetDisplay: json['vlLacreRetDisplay'] as String?,
  vlLacreRetPortaOptica: json['vlLacreRetPortaOptica'] as String?,
  vlLacreRetCubiculo1: json['vlLacreRetCubiculo1'] as String?,
  vlLacreRetCubiculo2: json['vlLacreRetCubiculo2'] as String?,
  vlLacreRetCxBarram1: json['vlLacreRetCxBarram1'] as String?,
  vlLacreRetCxBarram2: json['vlLacreRetCxBarram2'] as String?,
  vlLacreRetCxBarram3: json['vlLacreRetCxBarram3'] as String?,
  vlLacreRetCxBarram4: json['vlLacreRetCxBarram4'] as String?,
  vlLeitKwhPonta: json['vlLeitKwhPonta'] as String?,
  vlLeitKwhForaPonta: json['vlLeitKwhForaPonta'] as String?,
  vlLeitKwhGeral: json['vlLeitKwhGeral'] as String?,
  vlLeitKwhEspecial: json['vlLeitKwhEspecial'] as String?,
  vlLeitKwPonta: json['vlLeitKwPonta'] as String?,
  vlLeitKwFPonta: json['vlLeitKwFPonta'] as String?,
  vlLeitKwGeral: json['vlLeitKwGeral'] as String?,
  vlLeitKvarhPonta: json['vlLeitKvarhPonta'] as String?,
  vlLeitKvarhFPonta: json['vlLeitKvarhFPonta'] as String?,
  vlLeitKvarhGeral: json['vlLeitKvarhGeral'] as String?,
  vlConstLeitKwhPonta: json['vlConstLeitKwhPonta'] as String?,
  vlConstLeitKwhForaPonta: json['vlConstLeitKwhForaPonta'] as String?,
  vlConstLeitKwhGeral: json['vlConstLeitKwhGeral'] as String?,
  vlConstLeitKwPonta: json['vlConstLeitKwPonta'] as String?,
  vlConstLeitKwForaPonta: json['vlConstLeitKwForaPonta'] as String?,
  vlConstLeitKwGeral: json['vlConstLeitKwGeral'] as String?,
  vlConstLeitKvarhPonta: json['vlConstLeitKvarhPonta'] as String?,
  vlConsLeitKvarhForPonta: json['vlConsLeitKvarhForPonta'] as String?,
  vlConstLeitKvarhGeral: json['vlConstLeitKvarhGeral'] as String?,
  vlConstLeitEspecial: json['vlConstLeitEspecial'] as String?,
  itensInspecionados:
      (json['itensInspecionados'] as List<dynamic>?)
          ?.map(
            (e) => InspecaoItemConclusao.fromJson(e as Map<String, dynamic>),
          )
          .toList() ??
      const [],
  irregularidades:
      (json['irregularidades'] as List<dynamic>?)
          ?.map(
            (e) =>
                TipoIrregularidadeConclusao.fromJson(e as Map<String, dynamic>),
          )
          .toList() ??
      const [],
  acoesTomadas:
      (json['acoesTomadas'] as List<dynamic>?)
          ?.map((e) => AcaoTomadaConclusao.fromJson(e as Map<String, dynamic>))
          .toList() ??
      const [],
);

Map<String, dynamic> _$InspecaoConclusaoToJson(_InspecaoConclusao instance) =>
    <String, dynamic>{
      'id': instance.id,
      'dtInicio': instance.dtInicio.toIso8601String(),
      'dtFim': instance.dtFim?.toIso8601String(),
      'dsObservacao': instance.dsObservacao,
      'vlTc1': instance.vlTc1,
      'vlTc2': instance.vlTc2,
      'vlTp1': instance.vlTp1,
      'vlTp2': instance.vlTp2,
      'vlCorrenteMaxima': instance.vlCorrenteMaxima,
      'vlCorrenteMaximaFim': instance.vlCorrenteMaximaFim,
      'vlCorrenteDisjuntor': instance.vlCorrenteDisjuntor,
      'vlChaveProtecao': instance.vlChaveProtecao,
      'vlCaboEntrada': instance.vlCaboEntrada,
      'vlLacAdicPadAtivo1': instance.vlLacAdicPadAtivo1,
      'vlLacAdicPadAtivo2': instance.vlLacAdicPadAtivo2,
      'vlLacAdicPadAtivo3': instance.vlLacAdicPadAtivo3,
      'vlLacAdicPadAtivo4': instance.vlLacAdicPadAtivo4,
      'vlLacAdicPadReativo1': instance.vlLacAdicPadReativo1,
      'vlLacAdicPadReativo2': instance.vlLacAdicPadReativo2,
      'vlLacAdicPadReativo3': instance.vlLacAdicPadReativo3,
      'vlLacAdicPadReativo4': instance.vlLacAdicPadReativo4,
      'vlLacreAdicTcs1': instance.vlLacreAdicTcs1,
      'vlLacreAdicTcs2': instance.vlLacreAdicTcs2,
      'vlLacreAdicTcs3': instance.vlLacreAdicTcs3,
      'vlLacreAdicTcs4': instance.vlLacreAdicTcs4,
      'vlLacAdicCxDeriva1': instance.vlLacAdicCxDeriva1,
      'vlLacAdicCxDeriva2': instance.vlLacAdicCxDeriva2,
      'vlLacAdicChaveProt1': instance.vlLacAdicChaveProt1,
      'vlLacAdicChaveProt2': instance.vlLacAdicChaveProt2,
      'vlLacreAdicBorne1': instance.vlLacreAdicBorne1,
      'vlLacreAdicBorne2': instance.vlLacreAdicBorne2,
      'vlLacreAdicBorne3': instance.vlLacreAdicBorne3,
      'vlLacreAdicBorne4': instance.vlLacreAdicBorne4,
      'vlLacreAdicChaveAfer1': instance.vlLacreAdicChaveAfer1,
      'vlLacreAdicChaveAfer2': instance.vlLacreAdicChaveAfer2,
      'vlLacreAdicDemanda': instance.vlLacreAdicDemanda,
      'vlLacreAdicDisplay': instance.vlLacreAdicDisplay,
      'vlLacreAdicPortaOptica': instance.vlLacreAdicPortaOptica,
      'vlLacreAdicCubiculo1': instance.vlLacreAdicCubiculo1,
      'vlLacreAdicCubiculo2': instance.vlLacreAdicCubiculo2,
      'vlLacreAdicCxBarram1': instance.vlLacreAdicCxBarram1,
      'vlLacreAdicCxBarram2': instance.vlLacreAdicCxBarram2,
      'vlLacreAdicCxBarram3': instance.vlLacreAdicCxBarram3,
      'vlLacreAdicCxBarram4': instance.vlLacreAdicCxBarram4,
      'vlLacreRetPadAtivo1': instance.vlLacreRetPadAtivo1,
      'vlLacreRetPadAtivo2': instance.vlLacreRetPadAtivo2,
      'vlLacreRetPadAtivo3': instance.vlLacreRetPadAtivo3,
      'vlLacreRetPadAtivo4': instance.vlLacreRetPadAtivo4,
      'vlLacreRetPadReativo1': instance.vlLacreRetPadReativo1,
      'vlLacreRetPadReativo2': instance.vlLacreRetPadReativo2,
      'vlLacreRetPadReativo3': instance.vlLacreRetPadReativo3,
      'vlLacreRetPadReativo4': instance.vlLacreRetPadReativo4,
      'vlLacreRetTcs1': instance.vlLacreRetTcs1,
      'vlLacreRetTcs2': instance.vlLacreRetTcs2,
      'vlLacreRetTcs3': instance.vlLacreRetTcs3,
      'vlLacreRetTcs4': instance.vlLacreRetTcs4,
      'vlLacreRetCaixaDeriva1': instance.vlLacreRetCaixaDeriva1,
      'vlLacreRetCaixaDeriva2': instance.vlLacreRetCaixaDeriva2,
      'vlLacreRetChaveProtec1': instance.vlLacreRetChaveProtec1,
      'vlLacreRetChaveProtec2': instance.vlLacreRetChaveProtec2,
      'vlLacreRetBorne1': instance.vlLacreRetBorne1,
      'vlLacreRetBorne2': instance.vlLacreRetBorne2,
      'vlLacreRetBorne3': instance.vlLacreRetBorne3,
      'vlLacreRetBorne4': instance.vlLacreRetBorne4,
      'vlLacreRetChaveAfer1': instance.vlLacreRetChaveAfer1,
      'vlLacreRetChaveAfer2': instance.vlLacreRetChaveAfer2,
      'vlLacreRetDemanda': instance.vlLacreRetDemanda,
      'vlLacreRetDisplay': instance.vlLacreRetDisplay,
      'vlLacreRetPortaOptica': instance.vlLacreRetPortaOptica,
      'vlLacreRetCubiculo1': instance.vlLacreRetCubiculo1,
      'vlLacreRetCubiculo2': instance.vlLacreRetCubiculo2,
      'vlLacreRetCxBarram1': instance.vlLacreRetCxBarram1,
      'vlLacreRetCxBarram2': instance.vlLacreRetCxBarram2,
      'vlLacreRetCxBarram3': instance.vlLacreRetCxBarram3,
      'vlLacreRetCxBarram4': instance.vlLacreRetCxBarram4,
      'vlLeitKwhPonta': instance.vlLeitKwhPonta,
      'vlLeitKwhForaPonta': instance.vlLeitKwhForaPonta,
      'vlLeitKwhGeral': instance.vlLeitKwhGeral,
      'vlLeitKwhEspecial': instance.vlLeitKwhEspecial,
      'vlLeitKwPonta': instance.vlLeitKwPonta,
      'vlLeitKwFPonta': instance.vlLeitKwFPonta,
      'vlLeitKwGeral': instance.vlLeitKwGeral,
      'vlLeitKvarhPonta': instance.vlLeitKvarhPonta,
      'vlLeitKvarhFPonta': instance.vlLeitKvarhFPonta,
      'vlLeitKvarhGeral': instance.vlLeitKvarhGeral,
      'vlConstLeitKwhPonta': instance.vlConstLeitKwhPonta,
      'vlConstLeitKwhForaPonta': instance.vlConstLeitKwhForaPonta,
      'vlConstLeitKwhGeral': instance.vlConstLeitKwhGeral,
      'vlConstLeitKwPonta': instance.vlConstLeitKwPonta,
      'vlConstLeitKwForaPonta': instance.vlConstLeitKwForaPonta,
      'vlConstLeitKwGeral': instance.vlConstLeitKwGeral,
      'vlConstLeitKvarhPonta': instance.vlConstLeitKvarhPonta,
      'vlConsLeitKvarhForPonta': instance.vlConsLeitKvarhForPonta,
      'vlConstLeitKvarhGeral': instance.vlConstLeitKvarhGeral,
      'vlConstLeitEspecial': instance.vlConstLeitEspecial,
      'itensInspecionados': instance.itensInspecionados,
      'irregularidades': instance.irregularidades,
      'acoesTomadas': instance.acoesTomadas,
    };
