import 'dart:io';

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:smaservicos/app/data/models/acao_tomada/api/conclusao/acao_tomada_conclusao.dart';
import 'package:smaservicos/app/data/models/inspecao_item/conclusao/inspecao_item_conclusao.dart';
import 'package:smaservicos/app/data/models/tipo_irregularidade/api/conclusao/tipo_irregularidade_conclusao.dart';
import 'package:smaservicos/app/domain/entities/inspecao/inspecao.dart';

part 'inspecao_conclusao.freezed.dart';
part 'inspecao_conclusao.g.dart';

@freezed
abstract class InspecaoConclusao with _$InspecaoConclusao {

  const InspecaoConclusao._();
  const factory InspecaoConclusao({
    int? id,
    required DateTime dtInicio,
    @JsonKey(includeFromJson: false, includeToJson: false)
    Inspecao? inspecao,
    DateTime? dtFim,
    String? dsObservacao,
    String? vlTc1,
    String? vlTc2,
    String? vlTp1,
    String? vlTp2,
    String? vlCorrenteMaxima,
    String? vlCorrenteMaximaFim,
    String? vlCorrenteDisjuntor,
    String? vlChaveProtecao,
    String? vlCaboEntrada,
    String? vlLacAdicPadAtivo1,
    String? vlLacAdicPadAtivo2,
    String? vlLacAdicPadAtivo3,
    String? vlLacAdicPadAtivo4,
    String? vlLacAdicPadReativo1,
    String? vlLacAdicPadReativo2,
    String? vlLacAdicPadReativo3,
    String? vlLacAdicPadReativo4,
    String? vlLacreAdicTcs1,
    String? vlLacreAdicTcs2,
    String? vlLacreAdicTcs3,
    String? vlLacreAdicTcs4,
    String? vlLacAdicCxDeriva1,
    String? vlLacAdicCxDeriva2,
    String? vlLacAdicChaveProt1,
    String? vlLacAdicChaveProt2,
    String? vlLacreAdicBorne1,
    String? vlLacreAdicBorne2,
    String? vlLacreAdicBorne3,
    String? vlLacreAdicBorne4,
    String? vlLacreAdicChaveAfer1,
    String? vlLacreAdicChaveAfer2,
    String? vlLacreAdicDemanda,
    String? vlLacreAdicDisplay,
    String? vlLacreAdicPortaOptica,
    String? vlLacreAdicCubiculo1,
    String? vlLacreAdicCubiculo2,
    String? vlLacreAdicCxBarram1,
    String? vlLacreAdicCxBarram2,
    String? vlLacreAdicCxBarram3,
    String? vlLacreAdicCxBarram4,
    String? vlLacreRetPadAtivo1,
    String? vlLacreRetPadAtivo2,
    String? vlLacreRetPadAtivo3,
    String? vlLacreRetPadAtivo4,
    String? vlLacreRetPadReativo1,
    String? vlLacreRetPadReativo2,
    String? vlLacreRetPadReativo3,
    String? vlLacreRetPadReativo4,
    String? vlLacreRetTcs1,
    String? vlLacreRetTcs2,
    String? vlLacreRetTcs3,
    String? vlLacreRetTcs4,
    String? vlLacreRetCaixaDeriva1,
    String? vlLacreRetCaixaDeriva2,
    String? vlLacreRetChaveProtec1,
    String? vlLacreRetChaveProtec2,
    String? vlLacreRetBorne1,
    String? vlLacreRetBorne2,
    String? vlLacreRetBorne3,
    String? vlLacreRetBorne4,
    String? vlLacreRetChaveAfer1,
    String? vlLacreRetChaveAfer2,
    String? vlLacreRetDemanda,
    String? vlLacreRetDisplay,
    String? vlLacreRetPortaOptica,
    String? vlLacreRetCubiculo1,
    String? vlLacreRetCubiculo2,
    String? vlLacreRetCxBarram1,
    String? vlLacreRetCxBarram2,
    String? vlLacreRetCxBarram3,
    String? vlLacreRetCxBarram4,
    String? vlLeitKwhPonta,
    String? vlLeitKwhForaPonta,
    String? vlLeitKwhGeral,
    String? vlLeitKwhEspecial,
    String? vlLeitKwPonta,
    String? vlLeitKwFPonta,
    String? vlLeitKwGeral,
    String? vlLeitKvarhPonta,
    String? vlLeitKvarhFPonta,
    String? vlLeitKvarhGeral,
    String? vlConstLeitKwhPonta,
    String? vlConstLeitKwhForaPonta,
    String? vlConstLeitKwhGeral,
    String? vlConstLeitKwPonta,
    String? vlConstLeitKwForaPonta,
    String? vlConstLeitKwGeral,
    String? vlConstLeitKvarhPonta,
    String? vlConsLeitKvarhForPonta,
    String? vlConstLeitKvarhGeral,
    String? vlConstLeitEspecial,
    @Default([]) List<InspecaoItemConclusao> itensInspecionados,
    @Default([]) List<TipoIrregularidadeConclusao> irregularidades,
    @Default([]) List<AcaoTomadaConclusao> acoesTomadas,
    @JsonKey(includeFromJson: false, includeToJson: false)
    @Default([]) List<File> anexos
  }) = _InspecaoConclusao;

  factory InspecaoConclusao.fromJson(Map<String, dynamic> json) => _$InspecaoConclusaoFromJson(json);

  InspecaoConclusao copyFrom(InspecaoConclusao conclusao){
    return InspecaoConclusao(
        id: conclusao.id ?? id,
        dtInicio: conclusao.dtInicio,
        inspecao: conclusao.inspecao ?? inspecao,
        dtFim: conclusao.dtFim ?? dtFim,
        dsObservacao: conclusao.dsObservacao ?? dsObservacao,
        vlTc1: conclusao.vlTc1 ?? vlTc1,
        vlTc2: conclusao.vlTc2 ?? vlTc2,
        vlTp1: conclusao.vlTp1 ?? vlTp1,
        vlTp2: conclusao.vlTp2 ?? vlTp2,
        vlCorrenteMaxima: conclusao.vlCorrenteMaxima ?? vlCorrenteMaxima,
        vlCorrenteMaximaFim: conclusao.vlCorrenteMaximaFim ?? vlCorrenteMaximaFim,
        vlCorrenteDisjuntor: conclusao.vlCorrenteDisjuntor ?? vlCorrenteDisjuntor,
        vlChaveProtecao: conclusao.vlChaveProtecao ?? vlChaveProtecao,
        vlCaboEntrada: conclusao.vlCaboEntrada ?? vlCaboEntrada,
        vlLacAdicPadAtivo1: conclusao.vlLacAdicPadAtivo1 ?? vlLacAdicPadAtivo1,
        vlLacAdicPadAtivo2: conclusao.vlLacAdicPadAtivo2 ?? vlLacAdicPadAtivo2,
        vlLacAdicPadAtivo3: conclusao.vlLacAdicPadAtivo3 ?? vlLacAdicPadAtivo3,
        vlLacAdicPadAtivo4: conclusao.vlLacAdicPadAtivo4 ?? vlLacAdicPadAtivo4,
        vlLacAdicPadReativo1: conclusao.vlLacAdicPadReativo1 ?? vlLacAdicPadReativo1,
        vlLacAdicPadReativo2: conclusao.vlLacAdicPadReativo2 ?? vlLacAdicPadReativo2,
        vlLacAdicPadReativo3: conclusao.vlLacAdicPadReativo3 ?? vlLacAdicPadReativo3,
        vlLacAdicPadReativo4: conclusao.vlLacAdicPadReativo4 ?? vlLacAdicPadReativo4,
        vlLacreAdicTcs1: conclusao.vlLacreAdicTcs1 ?? vlLacreAdicTcs1,
        vlLacreAdicTcs2: conclusao.vlLacreAdicTcs2 ?? vlLacreAdicTcs2,
        vlLacreAdicTcs3: conclusao.vlLacreAdicTcs3 ?? vlLacreAdicTcs3,
        vlLacreAdicTcs4: conclusao.vlLacreAdicTcs4 ?? vlLacreAdicTcs4,
        vlLacAdicCxDeriva1: conclusao.vlLacAdicCxDeriva1 ?? vlLacAdicCxDeriva1,
        vlLacAdicCxDeriva2: conclusao.vlLacAdicCxDeriva2 ?? vlLacAdicCxDeriva2,
        vlLacAdicChaveProt1: conclusao.vlLacAdicChaveProt1 ?? vlLacAdicChaveProt1,
        vlLacAdicChaveProt2: conclusao.vlLacAdicChaveProt2 ?? vlLacAdicChaveProt2,
        vlLacreAdicBorne1: conclusao.vlLacreAdicBorne1 ?? vlLacreAdicBorne1,
        vlLacreAdicBorne2: conclusao.vlLacreAdicBorne2 ?? vlLacreAdicBorne2,
        vlLacreAdicBorne3: conclusao.vlLacreAdicBorne3 ?? vlLacreAdicBorne3,
        vlLacreAdicBorne4: conclusao.vlLacreAdicBorne4 ?? vlLacreAdicBorne4,
        vlLacreAdicChaveAfer1: conclusao.vlLacreAdicChaveAfer1 ?? vlLacreAdicChaveAfer1,
        vlLacreAdicChaveAfer2: conclusao.vlLacreAdicChaveAfer2 ?? vlLacreAdicChaveAfer2,
        vlLacreAdicDemanda: conclusao.vlLacreAdicDemanda ?? vlLacreAdicDemanda,
        vlLacreAdicDisplay: conclusao.vlLacreAdicDisplay ?? vlLacreAdicDisplay,
        vlLacreAdicPortaOptica: conclusao.vlLacreAdicPortaOptica ?? vlLacreAdicPortaOptica,
        vlLacreAdicCubiculo1: conclusao.vlLacreAdicCubiculo1 ?? vlLacreAdicCubiculo1,
        vlLacreAdicCubiculo2: conclusao.vlLacreAdicCubiculo2 ?? vlLacreAdicCubiculo2,
        vlLacreAdicCxBarram1: conclusao.vlLacreAdicCxBarram1 ?? vlLacreAdicCxBarram1,
        vlLacreAdicCxBarram2: conclusao.vlLacreAdicCxBarram2 ?? vlLacreAdicCxBarram2,
        vlLacreAdicCxBarram3: conclusao.vlLacreAdicCxBarram3 ?? vlLacreAdicCxBarram3,
        vlLacreAdicCxBarram4: conclusao.vlLacreAdicCxBarram4 ?? vlLacreAdicCxBarram4,
        vlLacreRetPadAtivo1: conclusao.vlLacreRetPadAtivo1 ?? vlLacreRetPadAtivo1,
        vlLacreRetPadAtivo2: conclusao.vlLacreRetPadAtivo2 ?? vlLacreRetPadAtivo2,
        vlLacreRetPadAtivo3: conclusao.vlLacreRetPadAtivo3 ?? vlLacreRetPadAtivo3,
        vlLacreRetPadAtivo4: conclusao.vlLacreRetPadAtivo4 ?? vlLacreRetPadAtivo4,
        vlLacreRetPadReativo1: conclusao.vlLacreRetPadReativo1 ?? vlLacreRetPadReativo1,
        vlLacreRetPadReativo2: conclusao.vlLacreRetPadReativo2 ?? vlLacreRetPadReativo2,
        vlLacreRetPadReativo3: conclusao.vlLacreRetPadReativo3 ?? vlLacreRetPadReativo3,
        vlLacreRetPadReativo4: conclusao.vlLacreRetPadReativo4 ?? vlLacreRetPadReativo4,
        vlLacreRetTcs1: conclusao.vlLacreRetTcs1 ?? vlLacreRetTcs1,
        vlLacreRetTcs2: conclusao.vlLacreRetTcs2 ?? vlLacreRetTcs2,
        vlLacreRetTcs3: conclusao.vlLacreRetTcs3 ?? vlLacreRetTcs3,
        vlLacreRetTcs4: conclusao.vlLacreRetTcs4 ?? vlLacreRetTcs4,
        vlLacreRetCaixaDeriva1: conclusao.vlLacreRetCaixaDeriva1 ?? vlLacreRetCaixaDeriva1,
        vlLacreRetCaixaDeriva2: conclusao.vlLacreRetCaixaDeriva2 ?? vlLacreRetCaixaDeriva2,
        vlLacreRetChaveProtec1: conclusao.vlLacreRetChaveProtec1 ?? vlLacreRetChaveProtec1,
        vlLacreRetChaveProtec2: conclusao.vlLacreRetChaveProtec2 ?? vlLacreRetChaveProtec2,
        vlLacreRetBorne1: conclusao.vlLacreRetBorne1 ?? vlLacreRetBorne1,
        vlLacreRetBorne2: conclusao.vlLacreRetBorne2 ?? vlLacreRetBorne2,
        vlLacreRetBorne3: conclusao.vlLacreRetBorne3 ?? vlLacreRetBorne3,
        vlLacreRetBorne4: conclusao.vlLacreRetBorne4 ?? vlLacreRetBorne4,
        vlLacreRetChaveAfer1: conclusao.vlLacreRetChaveAfer1 ?? vlLacreRetChaveAfer1,
        vlLacreRetChaveAfer2: conclusao.vlLacreRetChaveAfer2 ?? vlLacreRetChaveAfer2,
        vlLacreRetDemanda: conclusao.vlLacreRetDemanda ?? vlLacreRetDemanda,
        vlLacreRetDisplay: conclusao.vlLacreRetDisplay ?? vlLacreRetDisplay,
        vlLacreRetPortaOptica: conclusao.vlLacreRetPortaOptica ?? vlLacreRetPortaOptica,
        vlLacreRetCubiculo1: conclusao.vlLacreRetCubiculo1 ?? vlLacreRetCubiculo1,
        vlLacreRetCubiculo2: conclusao.vlLacreRetCubiculo2 ?? vlLacreRetCubiculo2,
        vlLacreRetCxBarram1: conclusao.vlLacreRetCxBarram1 ?? vlLacreRetCxBarram1,
        vlLacreRetCxBarram2: conclusao.vlLacreRetCxBarram2 ?? vlLacreRetCxBarram2,
        vlLacreRetCxBarram3: conclusao.vlLacreRetCxBarram3 ?? vlLacreRetCxBarram3,
        vlLacreRetCxBarram4: conclusao.vlLacreRetCxBarram4 ?? vlLacreRetCxBarram4,
        vlLeitKwhPonta: conclusao.vlLeitKwhPonta ?? vlLeitKwhPonta,
        vlLeitKwhForaPonta: conclusao.vlLeitKwhForaPonta ?? vlLeitKwhForaPonta,
        vlLeitKwhGeral: conclusao.vlLeitKwhGeral ?? vlLeitKwhGeral,
        vlLeitKwhEspecial: conclusao.vlLeitKwhEspecial ?? vlLeitKwhEspecial,
        vlLeitKwPonta: conclusao.vlLeitKwPonta ?? vlLeitKwPonta,
        vlLeitKwFPonta: conclusao.vlLeitKwFPonta ?? vlLeitKwFPonta,
        vlLeitKwGeral: conclusao.vlLeitKwGeral ?? vlLeitKwGeral,
        vlLeitKvarhPonta: conclusao.vlLeitKvarhPonta ?? vlLeitKvarhPonta,
        vlLeitKvarhFPonta: conclusao.vlLeitKvarhFPonta ?? vlLeitKvarhFPonta,
        vlLeitKvarhGeral: conclusao.vlLeitKvarhGeral ?? vlLeitKvarhGeral,
        vlConstLeitKwhPonta: conclusao.vlConstLeitKwhPonta ?? vlConstLeitKwhPonta,
        vlConstLeitKwhForaPonta: conclusao.vlConstLeitKwhForaPonta ?? vlConstLeitKwhForaPonta,
        vlConstLeitKwhGeral: conclusao.vlConstLeitKwhGeral ?? vlConstLeitKwhGeral,
        vlConstLeitKwPonta: conclusao.vlConstLeitKwPonta ?? vlConstLeitKwPonta,
        vlConstLeitKwForaPonta: conclusao.vlConstLeitKwForaPonta ?? vlConstLeitKwForaPonta,
        vlConstLeitKwGeral: conclusao.vlConstLeitKwGeral ?? vlConstLeitKwGeral,
        vlConstLeitKvarhPonta: conclusao.vlConstLeitKvarhPonta ?? vlConstLeitKvarhPonta,
        vlConsLeitKvarhForPonta: conclusao.vlConsLeitKvarhForPonta ?? vlConsLeitKvarhForPonta,
        vlConstLeitKvarhGeral: conclusao.vlConstLeitKvarhGeral ?? vlConstLeitKvarhGeral,
        vlConstLeitEspecial: conclusao.vlConstLeitEspecial ?? vlConstLeitEspecial,
        itensInspecionados: conclusao.itensInspecionados.isNotEmpty ? conclusao.itensInspecionados : itensInspecionados,
        irregularidades: conclusao.irregularidades.isNotEmpty ? conclusao.irregularidades : irregularidades,
        acoesTomadas: conclusao.acoesTomadas.isNotEmpty ? conclusao.acoesTomadas : acoesTomadas,
        anexos: conclusao.anexos.isNotEmpty ? conclusao.anexos : anexos
    );
  }

}